-- AlterTable
ALTER TABLE "Workspace" ADD COLUMN     "endDate" TIMESTAMP(3),
ADD COLUMN     "minStudyHours" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "streak" INTEGER NOT NULL DEFAULT 0;
